sonata_seo:
    encoding:         UTF-8
    page:
        default:          sonata.seo.page.default
        separator: ' - '
        title:            Miz Dara Unique - Unisex Wears Shop
        metas:
            name:
                keywords:             fashion clothes shoes bag watch man woman jeans gown pants shirt
                description:          Clothes,  shoes, bags, watches and all kind of accessories for men and women
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Miz Dara Unique - Unisex Wears Shop
                'og:description':     Fashion  for women and men

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"