easy_admin:
  entities:
    DeliveryFees:
      class: App\Entity\DeliveryFees
     
      list:
        actions: ['show', 'edit', 'delete'] 
        fields:
          - 'id'
          - 'transport'
          - 'ngCity'
          - 'ngState'
          - 'country'
          - 'continent'
      show:
        fields:
          - 'id'
          - 'transport'
          - 'maxDays'
          - 'ngCity'
          - 'ngState'
          - 'country'
          - 'continent'
          - 'fixedAmount'
          - 'amountByKm'
          - 'percentOfRawPrice'
          - 'freeForMoreThan'
          
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
      
        fields:   
          - 'transport'
          - 'maxDays'         
          - 'ngCity'
          - 'ngState'
          - 'country'          
          - 'continent'               
          - {property: 'fixedAmount', label: 'Fixed amount', type: 'money', type_options: { currency: 'NGN' }}
          - {property: 'amountByKm', type: 'money', type_options: { currency: 'NGN' }}
          - {property: 'percentOfRawPrice', label: 'Percent Of Raw Price ', type: 'percent'}
          - {property: 'freeForMoreThan', label: 'Free for more than', type: 'money', type_options: { currency: 'NGN' }}
          
      
            
        

