easy_admin:
  entities:
    Image:
      class: App\Entity\Image
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - {property: 'imageFile', type: 'vich_image'}
          - 'product'
          - 'tint' 
                        