easy_admin:
  entities:
    Stock:
      controller: App\Controller\EasyAdmin\StockController
      class: App\Entity\Stock
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - 'product'
          - 'size'
          - 'tint'
          - 'quantity'